const typeList =[ {
    type: 'normal',
    colour: '#A8A77AFF'},
    {type: 'fire',
    colour: '#EE8130FF'},
    {type: 'water',
    colour: '#6390F0FF'},
    {type: 'electric',
    colour: '#F7D02CFF'},
    {type: 'grass',
    colour: '#7AC74CFF'},
    {type: 'ice',
    colour: '#96D9D6FF'},
    {type: 'fighting',
    colour: '#C22E28FF'},
    {type: 'poison',
    colour: '#A33EA1FF'},
    {type: 'ground',
    colour: '#E2BF65FF'},
    {type: 'flying',
    colour: '#A98FF3FF'},
    {type: 'psychic',
    colour: '#F95587FF'},
    {type: 'bug',
    colour: '#A6B91AFF'},
    {type: 'rock',
    colour: '#B6A136FF'},
    {type: 'ghost',
    colour: '#735797FF'},
    {type: 'dragon',
    colour: '#6F35FCFF'},
    {type: 'dark',
    colour: '#705746FF'},
    {type: 'steel',
    colour: '#B7B7CEFF'},
    {type: 'fairy',
    colour: '#D685ADFF'}
]

export default typeList